# kuusi
# Copyright (C) 2014-2025 Christoph Müller  <mail@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


#include ./versions/simplified.toml
#include ./pages/pages.toml
#include ./facettes/administration.toml
#include ./facettes/help.toml
#include ./facettes/ideology.toml
#include ./facettes/installation.toml
#include ./facettes/linux-knowledge.toml
#include ./facettes/old-hardware.toml
#include ./facettes/pc-knowledge.toml
#include ./facettes/pricing.toml
#include ./facettes/privacy.toml
#include ./facettes/scenario.toml
#include ./facettes/scope.toml
#include ./facettes/updates.toml
#include ./facettes/ux.toml
#include ./facettes/lts.toml

#include ./choosables/choosables.toml

#include ./assignments/assignments.toml
#include ./assignments/lts.toml