# Generated by Django 2.1.2 on 2019-02-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.CharField(default='new-value', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GivenAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isImportant', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='distrochooser.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.CharField(default='new-value', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultDistroSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distrochooser.Distribution')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='resultdistroselection',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distrochooser.SelectionReason'),
        ),
        migrations.AddField(
            model_name='resultdistroselection',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distrochooser.UserSession'),
        ),
        migrations.AddField(
            model_name='givenanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distrochooser.UserSession'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distrochooser.Question'),
        ),
    ]
