# Generated by Django 2.1.2 on 2019-02-09 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 20, 38, 37, 401542)),
        ),
    ]
