# Generated by Django 2.1.2 on 2019-02-09 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0002_usersession_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='userAgent',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 20, 41, 21, 683534)),
        ),
    ]
