# Generated by Django 2.1.2 on 2019-02-09 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0003_auto_20190209_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='token',
            field=models.CharField(default=b'7NdVjW6rMAuHnMZl/BXVFw==', max_length=200),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 20, 44, 34, 735398)),
        ),
    ]
