# Generated by Django 2.1.2 on 2019-02-10 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0005_auto_20190210_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 15, 55, 32, 620497)),
        ),
    ]
