# Generated by Django 2.1.2 on 2019-02-23 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0006_auto_20190210_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isMultipleChoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 10, 48, 24, 353605)),
        ),
    ]
