# Generated by Django 2.1.2 on 2019-02-24 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0008_auto_20190224_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionreason',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 17, 53, 38, 893904)),
        ),
    ]
