# Generated by Django 2.1.2 on 2019-03-02 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0009_auto_20190224_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 16, 47, 2, 513538)),
        ),
    ]
