# Generated by Django 2.1.2 on 2019-03-02 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0012_auto_20190302_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdistroselection',
            name='isApprovedByUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultdistroselection',
            name='isDisApprovedByuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 17, 30, 58, 412774)),
        ),
    ]
