# Generated by Django 2.1.2 on 2019-03-02 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0013_auto_20190302_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 18, 20, 10, 34766)),
        ),
    ]
