# Generated by Django 2.1.2 on 2019-03-31 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0014_auto_20190302_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultdistroselection',
            old_name='isDisApprovedByuser',
            new_name='isDisApprovedByUser',
        ),
        migrations.AddField(
            model_name='distribution',
            name='bgColor',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='fgColor',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 13, 41, 51, 73111)),
        ),
    ]
