# Generated by Django 2.1.2 on 2019-03-31 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0015_auto_20190331_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='publicUrl',
            field=models.CharField(default='ThoseInsubstantialSprite', max_length=200),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 13, 56, 35, 370997)),
        ),
    ]
