# Generated by Django 2.1.2 on 2019-04-06 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0016_auto_20190331_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDistributionMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBlockingHit', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=300)),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='distrochooser.Answer')),
                ('blockedAnswers', models.ManyToManyField(related_name='blockedAnswers', to='distrochooser.Answer')),
                ('distro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='distrochooser.Distribution')),
            ],
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 11, 59, 0, 272404)),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='publicUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
