# Generated by Django 2.1.2 on 2019-04-06 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0017_auto_20190406_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionreason',
            name='blockedByOtherQuestions',
            field=models.ManyToManyField(blank=True, related_name='blockedSelectionAnswers', to='distrochooser.Answer'),
        ),
        migrations.AlterField(
            model_name='answerdistributionmatrix',
            name='blockedAnswers',
            field=models.ManyToManyField(blank=True, related_name='blockedAnswers', to='distrochooser.Answer'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 12, 48, 39, 270530)),
        ),
    ]
