# Generated by Django 2.1.2 on 2019-04-06 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0018_auto_20190406_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 12, 48, 42, 6829)),
        ),
    ]
