# Generated by Django 2.1.2 on 2019-04-06 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0019_auto_20190406_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectionreason',
            name='blockedByOtherQuestions',
        ),
        migrations.AddField(
            model_name='selectionreason',
            name='isRelatedBlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 13, 0, 52, 932236)),
        ),
    ]
