# Generated by Django 2.1.2 on 2019-04-06 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0020_auto_20190406_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerdistributionmatrix',
            name='blockedAnswers',
        ),
        migrations.AddField(
            model_name='answer',
            name='blockedAnswers',
            field=models.ManyToManyField(blank=True, related_name='blockedAnswersFromAnswer', to='distrochooser.Answer'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 16, 44, 45, 408958)),
        ),
    ]
