# Generated by Django 2.1.2 on 2019-04-06 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0021_auto_20190406_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdistributionmatrix',
            name='distros',
            field=models.ManyToManyField(blank=True, related_name='answerMatrixDistros', to='distrochooser.Distribution'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 21, 26, 43, 799337)),
        ),
    ]
