# Generated by Django 2.1.2 on 2019-04-06 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0022_auto_20190406_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerdistributionmatrix',
            name='distro',
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 21, 31, 4, 600452)),
        ),
    ]
