# Generated by Django 2.1.2 on 2019-04-06 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0023_auto_20190406_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdistributionmatrix',
            name='isNegativeHit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 22, 4, 14, 29993)),
        ),
    ]
