# Generated by Django 2.1.2 on 2019-04-07 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0025_auto_20190406_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 12, 1, 17, 788246)),
        ),
    ]
