# Generated by Django 2.1.2 on 2019-04-07 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0026_auto_20190407_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 12, 47, 25, 509286)),
        ),
    ]
