# Generated by Django 2.1.2 on 2019-05-30 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0029_auto_20190526_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='iconClass',
            field=models.TextField(default='far fa-circle'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 11, 30, 53, 255405)),
        ),
    ]
