# Generated by Django 2.1.2 on 2019-06-19 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0032_auto_20190610_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='remarks',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 19, 30, 44, 444522)),
        ),
    ]
