# Generated by Django 2.2.3 on 2019-07-26 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0033_auto_20190619_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdistroselection',
            name='checksDone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultdistroselection',
            name='checksToDo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 13, 17, 44, 439978)),
        ),
    ]
