# Generated by Django 2.2.3 on 2019-07-26 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0034_auto_20190726_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultdistroselection',
            name='checksDone',
        ),
        migrations.RemoveField(
            model_name='resultdistroselection',
            name='checksToDo',
        ),
        migrations.AddField(
            model_name='usersession',
            name='checksDone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='checksToDo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 13, 18, 24, 334142)),
        ),
    ]
