# Generated by Django 2.2.3 on 2019-08-22 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0035_auto_20190726_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isMediaQuestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 17, 3, 23, 409431)),
        ),
    ]
