# Generated by Django 2.1.2 on 2019-09-03 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0036_auto_20190822_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 7, 5, 29, 940844)),
        ),
    ]
