# Generated by Django 2.2.5 on 2019-09-08 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0037_auto_20190903_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 9, 48, 45, 117539)),
        ),
    ]
