# Generated by Django 2.2.5 on 2019-09-15 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0039_auto_20190908_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionreason',
            name='isImportant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 11, 35, 35, 346822)),
        ),
    ]
