# Generated by Django 2.2.5 on 2019-09-27 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0040_auto_20190915_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='referrer',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 15, 56, 29, 639706)),
        ),
    ]
