# Generated by Django 2.2.3 on 2019-12-13 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0041_auto_20190927_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 15, 33, 5, 621096)),
        ),
        migrations.AddIndex(
            model_name='answerdistributionmatrix',
            index=models.Index(fields=['answer'], name='distrochoos_answer__927c88_idx'),
        ),
        migrations.AddIndex(
            model_name='givenanswer',
            index=models.Index(fields=['session'], name='distrochoos_session_da95f1_idx'),
        ),
        migrations.AddIndex(
            model_name='resultdistroselection',
            index=models.Index(fields=['session'], name='distrochoos_session_ac28b5_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['token'], name='distrochoos_token_1737dc_idx'),
        ),
    ]
