# Generated by Django 2.2.3 on 2019-12-13 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0042_auto_20191213_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 15, 34, 44, 368201)),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['name'], name='distrochoos_name_04f653_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['identifier'], name='distrochoos_identif_107970_idx'),
        ),
        migrations.AddIndex(
            model_name='selectionreason',
            index=models.Index(fields=['resultSelection'], name='distrochoos_resultS_eb35e3_idx'),
        ),
    ]
