# Generated by Django 2.2.3 on 2019-12-13 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0043_auto_20191213_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 15, 34, 55, 255859)),
        ),
    ]
