# Generated by Django 2.2.3 on 2019-12-13 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0044_auto_20191213_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 15, 36, 6, 468121)),
        ),
        migrations.AddIndex(
            model_name='givenanswer',
            index=models.Index(fields=['answer'], name='distrochoos_answer__9ce12e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['publicUrl'], name='distrochoos_publicU_055ca0_idx'),
        ),
    ]
