# Generated by Django 2.2.3 on 2019-12-15 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0046_auto_20191213_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 11, 39, 55, 919541)),
        ),
    ]
