# Generated by Django 2.2.3 on 2019-12-15 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0047_auto_20191215_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 13, 49, 34, 528306)),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['msgid'], name='distrochoos_msgid_590a08_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['msgid'], name='distrochoos_msgid_6b7008_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['msgid'], name='distrochoos_msgid_2b2838_idx'),
        ),
    ]
