# Generated by Django 2.2.8 on 2020-01-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0050_auto_20191226_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='mediaSourcePath',
            field=models.TextField(blank=True, null=True),
        ),
    ]
