# Generated by Django 2.2.10 on 2020-05-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0055_auto_20200330_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='sessionToken',
            field=models.CharField(default='', max_length=200),
        ),
    ]
