# Generated by Django 2.2.10 on 2020-05-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0056_usersession_sessiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='commit',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
