# Generated by Django 2.2.10 on 2020-07-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0057_usersession_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='calculationEndTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
