# Generated by Django 2.2.10 on 2020-07-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0058_usersession_calculationendtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='remarksProcessed',
            field=models.BooleanField(default=False),
        ),
    ]
