# Generated by Django 2.2.28 on 2022-10-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0060_answer_orderindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='peculiarities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
