# Generated by Django 2.2.28 on 2022-08-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0060_answer_orderindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='questionType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
