# Generated by Django 2.2.28 on 2022-10-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0062_auto_20221022_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='givenpeculiarities',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='distrochooser.Question'),
            preserve_default=False,
        ),
    ]
