# Generated by Django 2.2.28 on 2022-10-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0063_givenpeculiarities_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='pecularities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
