# Generated by Django 2.2.28 on 2022-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0064_distribution_pecularities'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionreason',
            name='bonusHit',
            field=models.IntegerField(default=0),
        ),
    ]
