# Generated by Django 2.2.28 on 2022-10-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0065_selectionreason_bonushit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectionreason',
            name='bonusHit',
        ),
    ]
