# Generated by Django 4.1.4 on 2022-12-21 09:50

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("distrochooser", "0066_remove_selectionreason_bonushit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="peculiarities",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="pecularities",
        ),
        migrations.AddField(
            model_name="answer",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.DeleteModel(
            name="GivenPeculiarities",
        ),
    ]
