# Generated by Django 4.1.4 on 2022-12-21 10:23

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("distrochooser", "0067_remove_answer_peculiarities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="givenanswer",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
