# Generated by Django 4.1.4 on 2022-12-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0069_answer_additionaltext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="additionalText",
        ),
    ]
