# Generated by Django 4.1.4 on 2022-12-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0070_remove_answer_additionaltext"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="distribution",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="distribution",
            name="ratings",
            field=models.IntegerField(default=0),
        ),
    ]
