# Generated by Django 4.1.4 on 2022-12-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0071_distribution_percentage_distribution_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="positive_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
