# Generated by Django 4.1.4 on 2022-12-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0072_distribution_positive_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="clicks",
            field=models.IntegerField(default=0),
        ),
    ]
