# Generated by Django 4.1.4 on 2022-12-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0073_distribution_clicks"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="hardware_cores",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="usersession",
            name="hardware_frequency",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="usersession",
            name="hardware_is_mobile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersession",
            name="hardware_is_touch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersession",
            name="hardware_memory",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="usersession",
            name="hardware_storage",
            field=models.IntegerField(default=-1),
        ),
    ]
