# Generated by Django 4.1.4 on 2023-01-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0074_usersession_hardware_cores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="hardware_cores",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="distribution",
            name="hardware_frequency",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="distribution",
            name="hardware_has_mobile_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="distribution",
            name="hardware_has_touch_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="distribution",
            name="hardware_memory",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="distribution",
            name="hardware_storage",
            field=models.IntegerField(default=-1),
        ),
    ]
