# Generated by Django 4.1.4 on 2023-01-01 10:45

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("distrochooser", "0075_distribution_hardware_cores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="hardware_requirements_present",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
