# Generated by Django 4.1.4 on 2023-01-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0076_distribution_hardware_requirements_present_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distribution",
            name="hardware_has_mobile_support",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="hardware_is_mobile",
        ),
    ]
