# Generated by Django 4.1.4 on 2023-01-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "distrochooser",
            "0077_remove_distribution_hardware_has_mobile_support_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="data_id",
            field=models.TextField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
