# Generated by Django 4.1.4 on 2023-01-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0079_distribution_version_alter_distribution_data_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="founded",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
