# Generated by Django 4.1.4 on 2023-01-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0080_distribution_founded"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="age",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
