# Generated by Django 4.1.4 on 2023-01-07 14:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("distrochooser", "0082_answer_tag_prexfix"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectionreason",
            name="isTagOnlyHit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="answer",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
