# Generated by Django 4.1.4 on 2023-01-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0083_selectionreason_istagonlyhit_alter_answer_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selectionreason",
            name="isTagOnlyHit",
        ),
    ]
