# Generated by Django 4.1.4 on 2023-01-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0084_remove_selectionreason_istagonlyhit"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerdistributionmatrix",
            name="isTagOnlyHit",
            field=models.BooleanField(default=False),
        ),
    ]
