# Generated by Django 4.1.4 on 2023-02-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0085_answerdistributionmatrix_istagonlyhit"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="filter_by_hardware",
            field=models.BooleanField(default=False),
        ),
    ]
