# Generated by Django 4.1.4 on 2023-02-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distrochooser", "0086_usersession_filter_by_hardware"),
    ]

    operations = [
        migrations.AddField(
            model_name="givenanswer",
            name="isLessImportant",
            field=models.BooleanField(default=False),
        ),
    ]
