# Generated by Django 3.2.18 on 2023-03-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0088_selectionreason_islessimportant'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdistributionmatrix',
            name='isSuggestion',
            field=models.BooleanField(default=False),
        ),
    ]
