# Generated by Django 3.2.18 on 2023-03-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0090_auto_20230308_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersuggestion',
            name='distro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='distrochooser.distribution'),
        ),
        migrations.AddField(
            model_name='usersuggestion',
            name='new_mapping',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User_Suggestion_New', to='distrochooser.answerdistributionmatrix'),
        ),
        migrations.AddField(
            model_name='usersuggestion',
            name='old_mapping',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User_Suggestion_old', to='distrochooser.answerdistributionmatrix'),
        ),
    ]
