# Generated by Django 3.2.18 on 2023-03-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0091_auto_20230312_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggestion',
            name='old_mapping',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Suggestion_old', to='distrochooser.answerdistributionmatrix'),
        ),
    ]
