# Generated by Django 3.2.18 on 2023-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0093_alter_usersuggestion_new_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersuggestion',
            name='removal',
            field=models.BooleanField(default=False),
        ),
    ]
