# Generated by Django 3.2.18 on 2023-03-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0094_usersuggestion_removal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersuggestion',
            old_name='removal',
            new_name='is_removal',
        ),
    ]
