# Generated by Django 3.2.18 on 2023-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0095_rename_removal_usersuggestion_is_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdistributionmatrix',
            name='isNegativeSuggestion',
            field=models.BooleanField(default=False),
        ),
    ]
