# Generated by Django 3.2.18 on 2023-03-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0097_usersuggestionsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdistributionmatrix',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distrochooser.usersuggestionsession'),
        ),
        migrations.AddField(
            model_name='usersuggestion',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distrochooser.usersuggestionsession'),
            preserve_default=False,
        ),
    ]
