# Generated by Django 3.2.18 on 2023-03-26 11:15

import distrochooser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0098_auto_20230326_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersuggestionsession',
            name='editToken',
            field=models.CharField(default=distrochooser.models.get_token, max_length=200),
        ),
    ]
