# Generated by Django 3.2.18 on 2023-03-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0099_usersuggestionsession_edittoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersuggestionsession',
            old_name='editToken',
            new_name='readonlyToken',
        ),
    ]
