# Generated by Django 3.2.18 on 2023-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0100_rename_edittoken_usersuggestionsession_readonlytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='mediaGroup',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
