# Generated by Django 3.2.18 on 2023-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0101_answer_mediagroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='metric_translations',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
