# Generated by Django 3.2.18 on 2023-05-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('distrochooser', '0102_distribution_metric_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='metric_translations',
        ),
        migrations.CreateModel(
            name='AnswerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_translations', models.TextField(blank=True, default=None, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrochooser_answertag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
