# Generated by Django 3.2.18 on 2023-05-18 09:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('distrochooser', '0103_auto_20230518_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='distrochooser.AnswerTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='distrochooser.AnswerTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='distrochooser.AnswerTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
