# Generated by Django 3.2.18 on 2023-05-18 09:41

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('distrochooser', '0104_auto_20230518_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBaseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answertag',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='distrochooser_answertag_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answertag',
            name='object_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='object ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='distrochooser.AnswerTag', to='distrochooser.AnswerBaseTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='answertag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrochooser_answertag_items', to='distrochooser.answerbasetag'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='distrochooser.AnswerTag', to='distrochooser.AnswerBaseTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='distrochooser.AnswerTag', to='distrochooser.AnswerBaseTag', verbose_name='Tags'),
        ),
    ]
