# Generated by Django 3.2.18 on 2023-05-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrochooser', '0105_auto_20230518_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertag',
            name='tag_translations',
        ),
        migrations.AddField(
            model_name='answerbasetag',
            name='tag_translations',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
