# Generated by Django 5.2.6 on 2026-04-03 09:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import web.models.session
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Choosable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                ("clicked", models.IntegerField(default=0)),
                ("bg_color", models.CharField(default=None, max_length=10, null=True)),
                ("fg_color", models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.IntegerField(default=1)),
                ("col", models.IntegerField(default=1)),
                ("width", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="LanguageFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "voter_id",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_be_marked", models.BooleanField(default=False)),
                ("hide_text", models.BooleanField(default=False)),
                ("hide_help", models.BooleanField(default=False)),
                ("no_header", models.BooleanField(default=False)),
                ("text", models.CharField(blank=True, max_length=80, null=True)),
                ("title", models.CharField(blank=True, max_length=80, null=True)),
                ("help", models.CharField(blank=True, max_length=80, null=True)),
                ("hide_if_no_selections", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(default="bi bi-clipboard2-data", max_length=100),
                ),
                (
                    "next_page",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_next",
                        to="web.page",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="ChoosableMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_name",
                    models.CharField(
                        choices=[
                            ("AGE", "AGE"),
                            ("OPERATIONAL_CENTER", "OPERATIONAL_CENTER"),
                            ("LICENSES", "LICENSES"),
                            ("WEBSITE", "WEBSITE"),
                            ("LANGUAGES", "LANGUAGES"),
                            ("ARCHS", "ARCHS"),
                        ],
                        default="AGE",
                        max_length=25,
                    ),
                ),
                ("meta_value", models.CharField(default="A value", max_length=255)),
                (
                    "meta_choosable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choosablemeta_choosable",
                        to="web.choosable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=120)),
                ("topic", models.CharField(max_length=120)),
                (
                    "child_facettes",
                    models.ManyToManyField(blank=True, to="web.facette"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacetteAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=800, null=True
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "sources",
                    models.CharField(
                        blank=True, default=None, max_length=5000, null=True
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "POSITIVE"),
                            ("NEGATIVE", "NEGATIVE"),
                            ("NEUTRAL", "NEUTRAL"),
                            ("BLOCKING", "BLOCKING"),
                        ],
                        default="NEUTRAL",
                        max_length=20,
                    ),
                ),
                ("choosables", models.ManyToManyField(to="web.choosable")),
                ("facettes", models.ManyToManyField(to="web.facette")),
            ],
        ),
        migrations.CreateModel(
            name="FacetteBehaviour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "affected_objects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="facette_behaviour_objects",
                        to="web.facette",
                    ),
                ),
                (
                    "affected_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="facette_behaviour_subjects",
                        to="web.facette",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacetteSelectionWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
                ("topic", models.CharField(max_length=120)),
            ],
            bases=("web.widget",),
        ),
        migrations.CreateModel(
            name="FeedbackWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
            ],
            bases=("web.widget",),
        ),
        migrations.CreateModel(
            name="HTMLWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
                ("template", models.CharField(max_length=25)),
            ],
            bases=("web.widget",),
        ),
        migrations.CreateModel(
            name="MetaFilterWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
                ("structure", models.TextField(blank=True, default=None, null=True)),
            ],
            bases=("web.widget",),
        ),
        migrations.CreateModel(
            name="NavigationWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
            ],
            bases=("web.widget",),
        ),
        migrations.CreateModel(
            name="ResultListWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
            ],
            bases=("web.widget",),
        ),
        migrations.CreateModel(
            name="ResultShareWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
            ],
            bases=("web.widget",),
        ),
        migrations.CreateModel(
            name="SessionVersionWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
            ],
            bases=("web.widget",),
        ),
        migrations.AddField(
            model_name="widget",
            name="pages",
            field=models.ManyToManyField(blank=True, default=None, to="web.page"),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                (
                    "result_id",
                    models.CharField(
                        default=web.models.session.get_session_result_id, max_length=36
                    ),
                ),
                ("referrer", models.TextField(blank=True, default=None, null=True)),
                ("is_ack", models.BooleanField(default=False)),
                ("language_code", models.CharField(default="en", max_length=10)),
                (
                    "session_origin",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_sessionorigin",
                        to="web.session",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_version",
                        to="web.sessionversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageMarking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_error", models.BooleanField(default=False)),
                ("is_warning", models.BooleanField(default=False)),
                ("is_info", models.BooleanField(default=False)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagemarking_page",
                        to="web.page",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagemarking_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaFilterValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_filter_value_page",
                        to="web.page",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_filter_value_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LanguageFeedbackVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_positive", models.BooleanField(default=False)),
                (
                    "origin",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "language_feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_language_feedback",
                        to="web.languagefeedback",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_feedback_vote_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="languagefeedback",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="language_feedback_session",
                to="web.session",
            ),
        ),
        migrations.CreateModel(
            name="GivenFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="givenfeedback_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_positive", models.BooleanField(default=False)),
                (
                    "origin",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.facetteassignment",
                    ),
                ),
                (
                    "choosable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.choosable"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacetteSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(2),
                            django.core.validators.MinValueValidator(-2),
                        ],
                    ),
                ),
                (
                    "facette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facetteseletion_facette",
                        to="web.facette",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facetteseletion_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignmentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_positive", models.BooleanField(default=False)),
                (
                    "origin",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.facetteassignment",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_assignment",
                        to="web.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_key", models.CharField(max_length=30)),
                ("meta_value", models.CharField(max_length=30)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessionmeta_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="page",
            name="not_in_versions",
            field=models.ManyToManyField(blank=True, to="web.sessionversion"),
        ),
        migrations.CreateModel(
            name="FacetteRadioSelectionWidget",
            fields=[
                (
                    "facetteselectionwidget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.facetteselectionwidget",
                    ),
                ),
            ],
            bases=("web.facetteselectionwidget",),
        ),
    ]
