# Generated by Django 5.2.6 on 2026-04-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choosable",
            name="catalogue_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facette",
            name="catalogue_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facetteassignment",
            name="catalogue_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facettebehaviour",
            name="catalogue_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="catalogue_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sessionversion",
            name="catalogue_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="catalogue_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
