# Generated by Django 4.2.4 on 2023-08-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslateableFieldRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msg_id", models.CharField(max_length=50)),
                ("msg_str", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
