# Generated by Django 4.2.4 on 2023-08-19 08:58

from django.db import migrations

import web.models
class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_translateablefieldrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translateablefieldrecord",
            name="msg_str",
        ),
        migrations.AlterField(
            model_name="choosable",
            name="name",
            field=web.models.TranslateableField(
                help_text="A comment for translators to identify this value",
                max_length=120,
            ),
        ),
    ]
