# Generated by Django 5.2.6 on 2026-04-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_choosable_catalogue_id_facette_catalogue_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="choosablemeta",
            name="catalogue_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
