# Generated by Django 4.2.4 on 2023-08-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_remove_translateablefieldrecord_msg_str_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translateable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="choosable",
            name="id",
        ),
        migrations.AddField(
            model_name="choosable",
            name="translateable_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="web.translateable",
            ),
            preserve_default=False,
        ),
    ]
