# Generated by Django 5.2.14 on 2026-05-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_choosablemeta_catalogue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='imported_from_session',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
