# Generated by Django 5.2.14 on 2026-05-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_session_imported_from_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetteselection',
            name='imported_from_answer',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
