# Generated by Django 5.2.14 on 2026-06-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_facetteselection_imported_from_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ack_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
