# Generated by Django 5.2.14 on 2026-06-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_session_ack_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='entry_point',
            field=models.CharField(blank=True, choices=[('STARTPAGE', 'Start page'), ('ABOUT', 'About page'), ('CONTACT', 'Contact page'), ('PRIVACY', 'Privacy page')], default=None, max_length=10, null=True),
        ),
    ]
