# Generated by Django 5.2.14 on 2026-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_session_entry_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='entry_point',
            field=models.CharField(blank=True, choices=[('STARTPAGE', 'Start'), ('ABOUT', 'About'), ('CONTACT', 'Contact'), ('PRIVACY', 'Privacy')], default=None, max_length=10, null=True),
        ),
    ]
