# Generated by Django 4.2.4 on 2023-08-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="HTMLWidget",
            fields=[
                (
                    "translateable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.translateable",
                    ),
                ),
                ("template", models.CharField(choices=[], max_length=25)),
            ],
            bases=("web.translateable",),
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
