# Generated by Django 5.2.14 on 2026-06-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_session_entry_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='git_hash',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='matrix_hash',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='entry_point',
            field=models.CharField(blank=True, choices=[('STARTPAGE', 'Start'), ('ABOUT', 'About'), ('CONTACT', 'Contact'), ('PRIVACY', 'Privacy'), ('OUTGOING', 'Outgoing link')], default=None, max_length=10, null=True),
        ),
    ]
