# Generated by Django 4.2.4 on 2023-08-19 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_htmlwidget_widget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="htmlwidget",
            name="translateable_ptr",
        ),
        migrations.AddField(
            model_name="htmlwidget",
            name="widget_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="web.widget",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="htmlwidget",
            name="template",
            field=models.CharField(max_length=25),
        ),
    ]
