# Generated by Django 5.2.14 on 2026-06-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_session_git_hash_session_matrix_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='matrix_hash',
        ),
    ]
