# Generated by Django 4.2.4 on 2023-08-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_remove_htmlwidget_translateable_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HTMLWidget",
        ),
    ]
