# Generated by Django 5.2.14 on 2026-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_session_matrix_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='browser_family',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='os_family',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
