# Generated by Django 4.2.4 on 2023-08-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_delete_htmlwidget"),
    ]

    operations = [
        migrations.CreateModel(
            name="HTMLWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
                ("template", models.CharField(max_length=25)),
            ],
            bases=("web.widget",),
        ),
    ]
