# Generated by Django 4.2.4 on 2023-08-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_htmlwidget"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="col",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="widget",
            name="row",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="widget",
            name="width",
            field=models.IntegerField(default=1),
        ),
    ]
