# Generated by Django 5.2.14 on 2026-06-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_session_browser_family_session_is_bot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='browser_family',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_mobile',
        ),
        migrations.RemoveField(
            model_name='session',
            name='os_family',
        ),
    ]
