# Generated by Django 5.2.14 on 2026-07-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_session_browser_family_remove_session_is_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetteassignment',
            name='not_in_versions',
            field=models.ManyToManyField(blank=True, to='web.sessionversion'),
        ),
    ]
