# Generated by Django 5.2.14 on 2026-07-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_facetteassignment_not_in_versions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facetteassignment',
            name='not_in_versions',
        ),
    ]
