# Generated by Django 5.2.14 on 2026-07-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_facetteassignment_not_in_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='facette',
            name='not_in_versions',
            field=models.ManyToManyField(blank=True, to='web.sessionversion'),
        ),
    ]
