# Generated by Django 5.2.14 on 2026-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_facette_not_in_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosablemeta',
            name='meta_name',
            field=models.CharField(choices=[('AGE', 'AGE'), ('OPERATIONAL_CENTER', 'OPERATIONAL_CENTER'), ('LICENSES', 'LICENSES'), ('WEBSITE', 'WEBSITE'), ('LANGUAGES', 'LANGUAGES'), ('ARCHS', 'ARCHS'), ('MAJOR_UPDATE_INTERVAL', 'MAJOR_UPDATE_INTERVAL')], default='AGE', max_length=25),
        ),
    ]
