# Generated by Django 4.2.4 on 2023-08-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_navigationwidget"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="next_page",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_next",
                to="web.page",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="previous_page",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_previous",
                to="web.page",
            ),
        ),
    ]
