# Generated by Django 5.2.14 on 2026-08-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_choosablemeta_meta_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetteassignment',
            name='context_argument',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
