# Generated by Django 5.2.16 on 2026-08-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_facetteassignment_context_argument'),
    ]

    operations = [
        migrations.AddField(
            model_name='choosablemeta',
            name='meta_sources',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
