# Generated by Django 4.2.4 on 2023-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_remove_page_previous_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="pages",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="web.page"
            ),
        ),
    ]
