# Generated by Django 4.2.4 on 2023-08-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0018_widget_pages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widget",
            name="page",
        ),
    ]
