# Generated by Django 4.2.4 on 2023-08-19 15:29

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_facette_facetteselectionwidget"),
    ]

    operations = [
        migrations.AddField(
            model_name="facette",
            name="selectable_description",
            field=web.models.TranslateableField(
                default="foo",
                help_text="A comment for translators to identify this value",
                max_length=120,
            ),
            preserve_default=False,
        ),
    ]
