# Generated by Django 4.2.4 on 2023-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_facette_child_facettes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="pages",
            field=models.ManyToManyField(blank=True, default=None, to="web.page"),
        ),
    ]
