# Generated by Django 4.2.4 on 2023-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_alter_widget_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetteselectionwidget",
            name="topic",
            field=models.CharField(default="foo", max_length=120),
            preserve_default=False,
        ),
    ]
