# Generated by Django 4.2.4 on 2023-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_facetteselectionwidget_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facette",
            name="child_facettes",
            field=models.ManyToManyField(blank=True, to="web.facette"),
        ),
    ]
