# Generated by Django 4.2.4 on 2023-08-19 18:10

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0028_remove_facette_is_exclusive"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacetteBehaviour",
            fields=[
                (
                    "translateable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.translateable",
                    ),
                ),
                (
                    "description",
                    web.models.TranslateableField(
                        help_text="A comment for translators to identify this value",
                        max_length=120,
                    ),
                ),
                ("objects", models.ManyToManyField(blank=True, to="web.facette")),
            ],
            bases=("web.translateable",),
        ),
    ]
