# Generated by Django 4.2.4 on 2023-08-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0029_facettebehaviour"),
    ]

    operations = [
        migrations.AddField(
            model_name="facettebehaviour",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="facette_behaviour_subjects", to="web.facette"
            ),
        ),
        migrations.AlterField(
            model_name="facettebehaviour",
            name="objects",
            field=models.ManyToManyField(
                blank=True, related_name="facette_behaviour_objects", to="web.facette"
            ),
        ),
    ]
