# Generated by Django 4.2.4 on 2023-08-20 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0031_facettebehaviour_direction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
            ],
        ),
    ]
