# Generated by Django 4.2.4 on 2023-08-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0034_alter_session_result_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="require_session",
            field=models.BooleanField(default=False),
        ),
    ]
