# Generated by Django 4.2.4 on 2023-08-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0036_facetteselection"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetteselection",
            name="session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facetteseletion_session",
                to="web.session",
            ),
            preserve_default=False,
        ),
    ]
