# Generated by Django 4.2.4 on 2023-08-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0037_facetteselection_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facettebehaviour",
            old_name="objects",
            new_name="affected_objects",
        ),
        migrations.RenameField(
            model_name="facettebehaviour",
            old_name="subjects",
            new_name="affected_subjects",
        ),
    ]
