# Generated by Django 4.2.4 on 2023-08-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0038_rename_objects_facettebehaviour_affected_objects_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facettebehaviour",
            name="criticality",
            field=models.CharField(
                choices=[("WARNING", "WARNING"), ("ERROR", "ERROR"), ("INFO", "INFO")],
                default="ERROR",
                max_length=20,
            ),
        ),
    ]
