# Generated by Django 4.2.4 on 2023-08-20 09:05

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0041_resultlistrenderer"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacetteAssignment",
            fields=[
                (
                    "translateable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.translateable",
                    ),
                ),
                (
                    "description",
                    web.models.TranslateableField(
                        blank=True,
                        default=None,
                        help_text="A comment for translators to identify this value",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "POSITIVE"),
                            ("NEGATIVE", "NEGATIVE"),
                            ("NEUTRAL", "NEUTRAL"),
                        ],
                        default="NEUTRAL",
                        max_length=20,
                    ),
                ),
                ("choosables", models.ManyToManyField(to="web.choosable")),
                ("facettes", models.ManyToManyField(to="web.facette")),
            ],
            bases=("web.translateable",),
        ),
    ]
