# Generated by Django 4.2.4 on 2023-08-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0042_facetteassignment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FacetteAssignment",
        ),
    ]
