# Generated by Django 4.2.4 on 2023-08-20 09:23

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0044_facetteassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facetteassignment",
            name="description",
            field=web.models.TranslateableField(
                blank=True,
                default=None,
                help_text="A comment for translators to identify this value",
                max_length=255,
                null=True,
            ),
        ),
    ]
