# Generated by Django 4.2.4 on 2023-08-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0045_alter_facetteassignment_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResultListRenderer",
            new_name="ResultListWidget",
        ),
    ]
