# Generated by Django 4.2.4 on 2023-08-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0047_mainnavigationwidget"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MainNavigationWidget",
        ),
    ]
