# Generated by Django 4.2.4 on 2023-08-21 08:27

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0048_delete_mainnavigationwidget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "translateable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.translateable",
                    ),
                ),
                (
                    "name",
                    web.models.TranslateableField(
                        help_text="A comment for translators to identify this value",
                        max_length=120,
                    ),
                ),
                ("identifier", models.CharField(max_length=100)),
                (
                    "child_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_child_of",
                        to="web.category",
                    ),
                ),
            ],
            bases=("web.translateable",),
        ),
    ]
