# Generated by Django 4.2.4 on 2023-08-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0049_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="target_page",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_target_page",
                to="web.page",
            ),
        ),
    ]
