# Generated by Django 4.2.4 on 2023-08-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0050_category_target_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default="bi bi-clipboard2-data", max_length=100),
        ),
    ]
