# Generated by Django 4.2.4 on 2023-08-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0051_category_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="next_page",
            new_name="next_page_target",
        ),
    ]
