# Generated by Django 4.2.4 on 2023-08-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0052_rename_next_page_page_next_page_target"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="next_page_target",
            new_name="next_page",
        ),
    ]
