# Generated by Django 4.2.4 on 2023-08-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0054_sessionversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="version",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_version",
                to="web.sessionversion",
            ),
        ),
    ]
