# Generated by Django 4.2.4 on 2023-08-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0057_page_in_versions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="in_versions",
            new_name="not_in_versions",
        ),
    ]
