# Generated by Django 4.2.4 on 2023-08-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0060_alter_facetteselectionwidget_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facetteselectionwidget",
            name="description",
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
