# Generated by Django 4.2.4 on 2023-08-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0062_page_can_be_marked"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageMarking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagemarking_page",
                        to="web.page",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagemarking_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
    ]
