# Generated by Django 4.2.4 on 2023-08-26 09:12

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0063_pagemarking"),
    ]

    operations = [
        migrations.AddField(
            model_name="choosable",
            name="description",
            field=web.models.TranslateableField(
                blank=True,
                default=None,
                help_text="A comment for translators to identify this value",
                max_length=120,
                null=True,
            ),
        ),
    ]
