# Generated by Django 4.2.4 on 2023-08-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0064_choosable_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoosableMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_type",
                    models.CharField(
                        choices=[("TEXT", "TEXT")], default="TEXT", max_length=20
                    ),
                ),
            ],
        ),
    ]
