# Generated by Django 4.2.4 on 2023-08-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0065_choosablemeta"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChoosableMeta",
        ),
    ]
