# Generated by Django 4.2.4 on 2023-08-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0067_choosablemeta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choosablemeta",
            name="meta_name",
            field=models.CharField(
                choices=[("CREATED", "CREATED")], default="CREATED", max_length=25
            ),
        ),
    ]
