# Generated by Django 4.2.4 on 2023-08-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0068_alter_choosablemeta_meta_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="no_header",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="choosablemeta",
            name="meta_name",
            field=models.CharField(
                choices=[
                    ("CREATED", "CREATED"),
                    ("COUNTRY", "COUNTRY"),
                    ("LICENSES", "LICENSES"),
                    ("WEBSITE", "WEBSITE"),
                ],
                default="CREATED",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="choosablemeta",
            name="meta_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "TEXT"),
                    ("FLAG", "FLAG"),
                    ("LINK", "LINK"),
                    ("DATE", "DATE"),
                ],
                default="TEXT",
                max_length=20,
            ),
        ),
    ]
