# Generated by Django 4.2.4 on 2023-08-27 11:04

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0069_page_no_header_alter_choosablemeta_meta_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetteassignment",
            name="long_description",
            field=web.models.TranslateableField(
                blank=True,
                default=None,
                help_text="A comment for translators to identify this value",
                max_length=800,
                null=True,
            ),
        ),
    ]
