# Generated by Django 4.2.4 on 2023-08-27 11:09

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0070_facetteassignment_long_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="number",
            field=models.IntegerField(
                blank=True, default=None, null=True
            ),
        ),
    ]
