# Generated by Django 4.2.4 on 2023-08-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0071_session_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="session_origin",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_sessionorigin",
                to="web.session",
            ),
        ),
    ]
