# Generated by Django 4.2.4 on 2023-08-28 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0072_session_session_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetteselection",
            name="weight",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(2),
                    django.core.validators.MinValueValidator(-2),
                ],
            ),
        ),
    ]
