# Generated by Django 4.2.4 on 2023-08-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0073_facetteselection_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang_code", models.CharField(max_length=10)),
                ("lang_key", models.CharField(max_length=255)),
                ("lang_value", models.CharField(max_length=255)),
            ],
        ),
    ]
