# Generated by Django 4.2.4 on 2023-09-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0076_facette_is_invalidated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facette",
            name="is_invalidated",
        ),
    ]
