# Generated by Django 4.2.4 on 2023-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0078_translateable_is_invalidated"),
    ]

    operations = [
        migrations.AddField(
            model_name="translateable",
            name="invalidation_id",
            field=models.IntegerField(default=0),
        ),
    ]
