# Generated by Django 4.2.4 on 2023-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0079_translateable_invalidation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translateable",
            name="invalidation_id",
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
