# Generated by Django 4.2.4 on 2023-10-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0080_alter_translateable_invalidation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagemarking",
            name="is_error",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pagemarking",
            name="is_info",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pagemarking",
            name="is_warning",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="facettebehaviour",
            name="direction",
            field=models.CharField(
                choices=[
                    ("SUBJECT_TO_OBJECT", "SUBJECT_TO_OBJECT"),
                    ("OBJECT_TO_SUBJECT", "OBJECT_TO_SUBJECT"),
                    ("BIDIRECTIONAL", "BIDIRECTIONAL"),
                ],
                default="BIDIRECTIONAL",
                max_length=20,
            ),
        ),
    ]
