# Generated by Django 4.2.4 on 2023-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0081_pagemarking_is_error_pagemarking_is_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="valid_for",
            field=models.CharField(
                blank=True, default="latest", max_length=10, null=True
            ),
        ),
    ]
