# Generated by Django 4.2.4 on 2023-11-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0082_session_valid_for"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacetteRadioSelectionWidget",
            fields=[
                (
                    "facetteselectionwidget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.facetteselectionwidget",
                    ),
                ),
            ],
            bases=("web.facetteselectionwidget",),
        ),
    ]
