# Generated by Django 4.2.4 on 2023-11-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0084_remove_facetteassignment_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facette",
            name="description",
        ),
    ]
