# Generated by Django 4.2.4 on 2023-12-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0085_remove_facette_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choosablemeta",
            name="meta_title",
        ),
    ]
