# Generated by Django 4.2.4 on 2024-02-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0088_session_is_ack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="valid_for",
            field=models.CharField(
                blank=True, default="latest", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="translateable",
            name="catalogue_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="translateable",
            name="invalidation_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="translateablefieldrecord",
            name="msg_id",
            field=models.CharField(max_length=250),
        ),
    ]
