# Generated by Django 4.2.4 on 2024-03-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0089_alter_session_valid_for_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TranslationSuggestion",
        ),
    ]
