# Generated by Django 4.2.4 on 2024-03-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0090_delete_translationsuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="language_code",
            field=models.CharField(default="en", max_length=10),
        ),
    ]
