# Generated by Django 4.2.4 on 2024-03-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0091_session_language_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facetteassignment",
            name="long_description",
        ),
    ]
