# Generated by Django 4.2.4 on 2024-03-03 16:26

from django.db import migrations
import web.models.translateable


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0092_remove_facetteassignment_long_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetteassignment",
            name="long_description",
            field=web.models.translateable.TranslateableField(
                blank=True,
                default=None,
                help_text="A comment for translators to identify this value",
                max_length=800,
                null=True,
            ),
        ),
    ]
