# Generated by Django 4.2.4 on 2024-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0093_facetteassignment_long_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="translateablefieldrecord",
            name="model_type",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
