# Generated by Django 4.2.4 on 2024-05-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0094_translateablefieldrecord_model_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="title",
        ),
        migrations.RemoveField(
            model_name="translateablefieldrecord",
            name="po_block",
        ),
    ]
