# Generated by Django 4.2.4 on 2024-05-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0095_remove_page_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facetteselectionwidget",
            name="description",
        ),
    ]
