# Generated by Django 4.2.4 on 2024-05-19 11:55

from django.db import migrations
import web.models.translateable


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0096_remove_facetteselectionwidget_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetteselectionwidget",
            name="description",
            field=web.models.translateable.TranslateableField(
                blank=True,
                default=None,
                help_text="A comment for translators to identify this value",
                max_length=120,
                null=True,
            ),
        ),
    ]
