# Generated by Django 4.2.4 on 2024-05-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0098_page_help_text_page_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="help_text",
            new_name="help",
        ),
    ]
