# Generated by Django 4.2.4 on 2024-05-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0099_rename_help_text_page_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="hide_text",
            field=models.BooleanField(default=False),
        ),
    ]
