# Generated by Django 4.2.4 on 2024-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0100_page_hide_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="hide_help",
            field=models.BooleanField(default=False),
        ),
    ]
