# Generated by Django 4.2.4 on 2024-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0101_page_hide_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facette",
            name="topic",
            field=models.CharField(max_length=120),
        ),
    ]
