# Generated by Django 4.2.4 on 2024-05-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0102_alter_facette_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="choosable",
            name="clicked",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="facetteassignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "POSITIVE"),
                    ("NEGATIVE", "NEGATIVE"),
                    ("NEUTRAL", "NEUTRAL"),
                    ("BLOCKING", "BLOCKING"),
                ],
                default="NEUTRAL",
                max_length=20,
            ),
        ),
    ]
