# Generated by Django 4.2.4 on 2024-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0103_choosable_clicked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="css_classes",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
