# Generated by Django 4.2.4 on 2024-05-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0104_page_css_classes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="require_session",
        ),
    ]
