# Generated by Django 4.2.4 on 2024-05-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0106_alter_session_valid_for"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translateable",
            name="invalidation_id",
        ),
    ]
