# Generated by Django 4.2.4 on 2024-05-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0107_remove_translateable_invalidation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="valid_for",
        ),
    ]
