# Generated by Django 4.2.4 on 2024-05-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0108_remove_session_valid_for"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_positive", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.facetteassignment",
                    ),
                ),
                (
                    "choosable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.choosable"
                    ),
                ),
            ],
        ),
    ]
