# Generated by Django 4.2.4 on 2024-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0109_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="choosable",
            name="bg_color",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="choosable",
            name="fg_color",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
