# Generated by Django 4.2.4 on 2024-05-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0110_choosable_bg_color_choosable_fg_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="display_mode",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
