# Generated by Django 4.2.4 on 2024-06-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0111_session_display_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choosablemeta",
            name="meta_name",
            field=models.CharField(
                choices=[
                    ("AGE", "AGE"),
                    ("COUNTRY", "COUNTRY"),
                    ("LICENSES", "LICENSES"),
                    ("WEBSITE", "WEBSITE"),
                ],
                default="AGE",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="SessionMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_key", models.CharField(max_length=10)),
                ("meta_value", models.CharField(max_length=10)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessionmeta_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
    ]
