# Generated by Django 4.2.4 on 2024-07-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0112_alter_choosablemeta_meta_name_sessionmeta"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="filter_string",
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
