# Generated by Django 4.2.4 on 2024-07-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0113_session_filter_string"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="filter_string",
        ),
    ]
