# Generated by Django 4.2.4 on 2024-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0115_page_hide_if_no_selections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="display_mode",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
