# Generated by Django 4.2.14 on 2024-10-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0118_remove_session_display_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.session",
            ),
            preserve_default=False,
        ),
    ]
