# Generated by Django 4.2.14 on 2024-12-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0119_feedback_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_session",
                to="web.session",
            ),
        ),
    ]
