# Generated by Django 4.2.14 on 2025-02-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0120_alter_feedback_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_feedback_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
    ]
