# Generated by Django 4.2.14 on 2025-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0121_languagefeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagefeedback",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
