# Generated by Django 4.2.14 on 2025-02-06 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0122_languagefeedback_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageFeedbackVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_positive", models.BooleanField(default=False)),
                (
                    "language_feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_language_feedback",
                        to="web.languagefeedback",
                    ),
                ),
            ],
        ),
    ]
