# Generated by Django 4.2.14 on 2025-02-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0123_languagefeedbackvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagefeedbackvote",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="language_feedback_vote_session",
                to="web.session",
            ),
            preserve_default=False,
        ),
    ]
