# Generated by Django 4.2.14 on 2025-02-08 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0124_languagefeedbackvote_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaFilterWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
                ("structure", models.TextField(blank=True, default=None)),
            ],
            bases=("web.widget",),
        ),
    ]
