# Generated by Django 4.2.14 on 2025-02-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0125_metafilterwidget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metafilterwidget",
            name="structure",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
