# Generated by Django 4.2.14 on 2025-02-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0127_metafiltervalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetteassignment",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
