# Generated by Django 4.2.14 on 2025-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0129_assignmentfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentfeedback",
            name="is_positive",
            field=models.BooleanField(default=False),
        ),
    ]
