# Generated by Django 4.2.14 on 2025-02-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0131_metafilterwidget_key_alter_session_result_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metafilterwidget",
            name="key",
        ),
    ]
