# Generated by Django 4.2.14 on 2025-03-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0133_metafiltervalue_origin_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metafiltervalue",
            old_name="origin_page",
            new_name="page",
        ),
    ]
