# Generated by Django 4.2.14 on 2025-03-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0134_rename_origin_page_metafiltervalue_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagefeedbackvote",
            name="origin",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="metafiltervalue",
            name="page",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta_filter_value_page",
                to="web.page",
            ),
        ),
    ]
