# Generated by Django 4.2.14 on 2025-03-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0135_languagefeedbackvote_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentfeedback",
            name="origin",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
