# Generated by Django 4.2.14 on 2025-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0136_assignmentfeedback_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="origin",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
