# Generated by Django 5.1.7 on 2025-03-11 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0137_feedback_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.widget",
                    ),
                ),
            ],
            bases=("web.widget",),
        ),
    ]
