# Generated by Django 5.1.7 on 2025-03-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0138_feedbackwidget"),
    ]

    operations = [
        migrations.CreateModel(
            name="GivenFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="givenfeedback_session",
                        to="web.session",
                    ),
                ),
            ],
        ),
    ]
