# Generated by Django 5.1.7 on 2025-04-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0139_givenfeedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="number",
        ),
        migrations.AlterField(
            model_name="choosablemeta",
            name="meta_name",
            field=models.CharField(
                choices=[
                    ("AGE", "AGE"),
                    ("COUNTRY", "COUNTRY"),
                    ("LICENSES", "LICENSES"),
                    ("WEBSITE", "WEBSITE"),
                    ("LANGUAGES", "LANGUAGES"),
                ],
                default="AGE",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="choosablemeta",
            name="meta_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "TEXT"),
                    ("FLAG", "FLAG"),
                    ("LINK", "LINK"),
                    ("HIDDEN", "HIDDEN"),
                    ("DATE", "DATE"),
                ],
                default="TEXT",
                max_length=20,
            ),
        ),
    ]
