# Generated by Django 5.1.7 on 2025-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0141_alter_session_result_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagefeedback",
            name="voter_id",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
