# Generated by Django 5.1.7 on 2025-05-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0142_languagefeedback_voter_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choosablemeta",
            name="meta_type",
        ),
    ]
