# Generated by Django 5.1.7 on 2025-05-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0143_remove_choosablemeta_meta_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facetteassignment",
            old_name="long_description",
            new_name="description",
        ),
    ]
