# Generated by Django 5.1.7 on 2025-06-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0144_rename_long_description_facetteassignment_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="child_of",
        ),
    ]
