# Generated by Django 5.1.7 on 2025-06-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0145_remove_category_child_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="icon",
            field=models.CharField(default="bi bi-clipboard2-data", max_length=100),
        ),
    ]
