# Generated by Django 5.1.7 on 2025-06-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0147_page_title_delete_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facette",
            old_name="selectable_description",
            new_name="description",
        ),
    ]
