# Generated by Django 5.1.7 on 2025-06-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0148_rename_selectable_description_facette_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choosable",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
