# Generated by Django 5.1.7 on 2025-06-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0149_alter_choosable_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionversion",
            old_name="version_name",
            new_name="description",
        ),
    ]
