# Generated by Django 5.1.7 on 2025-06-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0150_rename_version_name_sessionversion_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="css_classes",
        ),
    ]
