# Generated by Django 5.1.7 on 2025-06-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0151_remove_page_css_classes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facettebehaviour",
            name="direction",
        ),
    ]
