# Generated by Django 5.1.7 on 2025-06-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0152_remove_facettebehaviour_direction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facettebehaviour",
            name="criticality",
        ),
        migrations.RemoveField(
            model_name="facettebehaviour",
            name="description",
        ),
    ]
