# Generated by Django 5.2.6 on 2026-01-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0153_remove_facettebehaviour_criticality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetteassignment",
            name="sources",
            field=models.CharField(
                blank=True, default=None, max_length=5000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="choosablemeta",
            name="meta_name",
            field=models.CharField(
                choices=[
                    ("AGE", "AGE"),
                    ("COUNTRY", "COUNTRY"),
                    ("LICENSES", "LICENSES"),
                    ("WEBSITE", "WEBSITE"),
                    ("LANGUAGES", "LANGUAGES"),
                    ("ARCHS", "ARCHS"),
                ],
                default="AGE",
                max_length=25,
            ),
        ),
    ]
