# distrochooser
# Copyright (C) 2014-2026 Christoph Müller <distrochooser@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# if the user demands that there is no AI used in the distribution
# this will be interpreted as a blocking issue which
# cannot be overruled by other assignments

[assignment.has-ai-policy]
facettes = ["no-ai"]
choosables = [
    "Fedora",
    "Deepin"
]
how = "blocking"
sources = [
    "Fedora;https://docs.fedoraproject.org/en-US/council/policy/ai-contribution-policy/",
    "Deepin;https://www.theregister.com/2026/01/23/deepin_25010/",
]

[assignment.has-no-ai-policy]
facettes = ["no-ai"]
choosables = [
    "Gentoo"
]
how = "positive"
sources = [
    "Gentoo;https://wiki.gentoo.org/wiki/Project:Council/AI_policy"
]

# The debian project decided on a resolution for responsible AI usage.
# As the facette "no-ai" explicitly asks for "there is no AI",
# This will result in a negative match as the project resolution
# relies on the personal responsibility of the contributor, but not 
# explicitly forbirds AI usage per se.
[assignment.debian-ai-usage]
facettes = ["no-ai"]
choosables = [
    "Debian"
]
how = "negative"
sources = [
    "Debian;https://www.debian.org/vote/2026/vote_002"
]
